export * from './patient.model';
export * from './profesional.model';
export * from './appointment.model';
export * from './auth.model';
export * from './odontograma.model';
export * from './periodontograma.model';
export * from './dashboard.model';
export * from './configuration.model';
export * from './invitation.model';